name: Build Itzy
on: push

jobs:
  build:
    name: Build Itzy
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        build-type: [Debug, Release]
        os: [ubuntu-latest, macos-latest, windows-latest]
        cc: [gcc-8, gcc-9, clang-8, clang-9]
    env:
      CMAKE_GENERATOR: Ninja
      GITHUB_TOKEN: ${{ github.token }}
      CC: ${{ matrix.cc }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install CMake and Ninja
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade cmake ninja
      - name: Configure
        run: >-
          cmake -Bbuild -S${{ github.workspace }} 
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} 
      - name: Build
        run: cmake --build build
